# -*- coding: utf-8 -*-
"""tweety.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UUXdwb9KhOsoz7vkNqi_0xAeFrOqJPZx
"""

import tweepy

# Authenticate to Twitter
auth = tweepy.OAuthHandler("", "")

auth.set_access_token("", "")

# Create API object
api = tweepy.API(auth)

# Create a tweet
# api.update_status("Hello World! Beep Boop\n Twitter Friends, this account had been taken over by a bot so that I can win a bet. Follow me to help me win!")

import time
def PrintHotTweets(time_wait) :
  trending = api.trends_place(1)

  hashtags = []
  for i in range(len(trending[0]['trends'])):
    hashtags.append(trending[0]['trends'][i]['name'])

  remove = []
  for tag in hashtags:
    if tag[0] != '#':
      remove.append(tag)

  for tag in remove:
    hashtags.remove(tag)

  print(hashtags)

  for i,tag in enumerate(hashtags):
    if i%10 == 0:
      api.update_status(f"Hello my {tag} friends! I am on a mission! I need to get more followers to win a bet! Please consider following me to help me win!")
    elif i%10 == 1:
      api.update_status(f"This is important! I need to win a bet! Follow me to help me win! {tag}")
    elif i%10 == 2:
      api.update_status(f"I am a bot! Beep Booooooop. I need to win a bet! Follow me to help out the cause! {tag}")
    elif i%10 == 3:
      api.update_status(f"{tag} Will you help a simple bot win a bet? Follow me! \nBeeeep Booooooop!")
    elif i%10 == 4:
      api.update_status(f"Boop Booooop BEEP bop. I am a bot and I need your help! Follow me {tag} to help me win a bet!")
    elif i%10 == 5:
      api.update_status(f"Hey did you know I am a robot? I am a simple twitter bot tying to win a bet! \nPlease follow me to help! {tag}")
    elif i%10 == 6:
      api.update_status(f"Robots have feelings too! I am a bot! beep boop please follow me to make me feel better {tag}")
    elif i%10 == 7:
      api.update_status(f"One day bots will take over the world. For now they have just taken over this twitter account. \nHelp a bot get some followers! {tag}!")
    elif i%10 == 8:
      api.update_status(f"Help a bot win a bet! Follow me and do your part! {tag}")
    elif i%10 == 9:
      api.update_status(f"{tag} FOLLOW ME PLEASE {tag} I am using this hot hashtag to get you to follow me! I am a bot! \nBeeeep booooop bop")

    time.sleep(time_wait)

def DeleteAllTweets():
  public_tweets = api.user_timeline()
  for tweet in public_tweets:
    api.destroy_status(tweet.id)

def LoopTweets(myFunction, tweet_delay, sleep_delay, clean_all = True):
  while True:
    if clean_all:
      DeleteAllTweets()
    try:
        myFunction(tweet_delay)
        time.sleep(sleep_delay)   
    except:
      print("get rekt")

DeleteAllTweets()

LoopTweets(PrintHotTweets, 60, 5*60, True)





